version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://nestuser:nestpassword@postgres:5432/nestdb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start

volumes:
  postgres_data:
